name: Lint
on:
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - uses: TrueBrain/actions-flake8@v2
        with:
          flake8_version: 6.0.0
          plugins: flake8-isort==6.1.1 flake8-quotes==3.4.0

  ruff-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/ruff-action@v4.1.0
        with:
          version: "~=0.16.3"
          args: format --check --diff --output-format=github

  requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Check requirements.in order
        run: |
          shopt -s nullglob
          for f in requirements/*.in; do
            LANG=C sort -c "$f"
          done
