# Reusable workflow for reporting build status
name: Status

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      build_tag:
        required: true
        type: string
      success:
        required: true
        type: boolean

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      # Optional
      AWS_ROLE_ARN:
        required: false
      AWS_REGION:
        required: false


jobs:
  report-success:
    if: inputs.success
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v2

      - name: Load environment defaults
        run: cat .github/workflows/config-public/${{ inputs.environment }}.env >> $GITHUB_ENV

      - uses: actions/download-artifact@v2

      - name: Upload success labels
        run: |
          mkdir -p buildreport
          echo '{"schemaVersion": 1, "label": "Build Status", "message": "Success", "color": "success"}' > buildreport/buildstatus.json
          echo '{"schemaVersion": 1, "label": "Last Successful Build", "message": "${{ inputs.build_tag }}", "color": "success"}'  > buildreport/lastgoodbuild.json
          echo '{"schemaVersion": 1, "label": "Last Build", "message": "${{ inputs.build_tag }}", "color": "success"}' > buildreport/lastbuild.json
          aws s3 cp buildreport/ "s3://${CODE_BUCKET}/thin-egress-app/" \
              --recursive \
              --metadata-directive REPLACE \
              --cache-control no-cache \
              --expires '2016-06-14T00:00:00Z' \
              --content-type 'application/json' \
              --acl public-read

  report-failures:
    if: ${{ !inputs.success }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v2

      - name: Load environment defaults
        run: cat .github/workflows/config-public/${{ inputs.environment }}.env >> $GITHUB_ENV

      - uses: actions/download-artifact@v2

      - name: Upload failure labels
        run: |
          mkdir -p buildreport
          echo '{"schemaVersion": 1, "label": "Build Status", "message": "Failed!", "color": "critical"}' > buildreport/buildstatus.json
          echo '{"schemaVersion": 1, "label": "Last Build", "message": "${{ inputs.build_tag }}", "color": "critical"}' > buildreport/lastbuild.json
          aws s3 cp buildreport/ "s3://${CODE_BUCKET}/thin-egress-app/" \
              --recursive \
              --metadata-directive REPLACE \
              --cache-control no-cache \
              --expires '2016-06-14T00:00:00Z' \
              --content-type 'application/json' \
              --acl public-read
