name: End-to-End Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/re-build.yml
    with:
      environment: prod

  test-e2e:
    needs:
      - build
    if: ${{ vars.RUN_TESTS }}
    uses: ./.github/workflows/re-test-e2e.yml
    with:
      environment: test
    secrets: inherit

  status:
    if: always()
    needs:
      - build
      - test-e2e
    uses: ./.github/workflows/re-status.yml
    with:
      environment: prod
      build_tag: ${{ needs.build.outputs.version }}
      success: ${{ needs.build.result != 'failure' && needs.test-e2e.result != 'failure' }}
    secrets: inherit
